sudo: required
services:
  - docker

before_install:
  - docker build -t maxoptland/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maxoptland/react-test npm test -- --coverage

after_success:
  - docker_build -t maxoptland/multi-client ./client
  - docker_build -t maxoptland/multi-nginx ./ nginx
  - docker_build -t maxoptland/multi-server ./ server
  - docker_build -t maxoptland/multi-worker ./ worker
  # Take those images and push them to Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push maxoptland/multi-client
  - docker push maxoptland/multi-nginx
  - docker push maxoptland/multi-server
  - docker push maxoptland/multi-worker